# Generated by Django 4.0.5 on 2022-06-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_post_user_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank='true', upload_to='post/'),
        ),
    ]
